version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  post-service:
    build: ./post-service
    ports:
      - "8002:8000"
    depends_on:
      - postgres

  comment-service:
    build: ./comment-service
    ports:
      - "8003:8000"
    depends_on:
      - postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - post-service
      - comment-service

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres-data:
  grafana-data: