global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'post-service'
    static_configs:
      - targets: ['post-service:8000']

  - job_name: 'comment-service'
    static_configs:
      - targets: ['comment-service:8000']